// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VrcUrlPooling;

#nullable disable

namespace VrcUrlPooling.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250530195440_AddImageSizing")]
    partial class AddImageSizing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VrcUrlPooling.Models.TextUrlSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowCache")
                        .HasColumnType("tinyint(1)")
                        .HasComment("对于图片，允许缓存结果");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxSize")
                        .HasColumnType("int")
                        .HasComment("如果有，就当成图片解析并且在返回时保证图片长宽不超过这个大小，max 2048，0 则不作为图片出来");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(5000)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Url");

                    b.ToTable("TextUrls", t =>
                        {
                            t.HasComment("用于文字和图片");
                        });
                });

            modelBuilder.Entity("VrcUrlPooling.Models.VideoUrlSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(5000)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Url");

                    b.ToTable("VideoUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
